package com.em.earthquakemonitor.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.em.earthquakemonitor.greendao.Earthquakes;

import com.em.earthquakemonitor.greendao.EarthquakesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig earthquakesDaoConfig;

    private final EarthquakesDao earthquakesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        earthquakesDaoConfig = daoConfigMap.get(EarthquakesDao.class).clone();
        earthquakesDaoConfig.initIdentityScope(type);

        earthquakesDao = new EarthquakesDao(earthquakesDaoConfig, this);

        registerDao(Earthquakes.class, earthquakesDao);
    }
    
    public void clear() {
        earthquakesDaoConfig.getIdentityScope().clear();
    }

    public EarthquakesDao getEarthquakesDao() {
        return earthquakesDao;
    }

}
